services:
  mamabloemetjes:
    networks:
      - mamabloemetjes-net
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mamabloemetjes
    env_file:
      - .env
    volumes:
      - .env:/app/.env:ro
      - go-build-cache:/root/.cache/go-build
      - go-mod-cache:/go/pkg/mod
    ports:
      - "8081:8081"
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4 # optional backup DNS

networks:
  mamabloemetjes-net:
    external: true

volumes:
  go-build-cache:
  go-mod-cache:
